### ISSUE TITLE
Missing Linux releases for 0.6.0

### ISSUE THREAD

**Issue by hmatejx** [eosrio/simpleos#16]
The following builds are missing for version 0.6.0:
- [Linux AppImage](https://github.com/eosrio/simpleos/releases/download/v0.6.0/simpleos-0.6.0-x86_64.AppImage)
- [Linux DEB](https://github.com/eosrio/simpleos/releases/download/v0.6.0/simpleos-0.6.0-x86_64.AppImage)

**Comment by eosrio** [comment]
There was a issue with the build script, its fixed now. Thanks for the report!
https://github.com/eosrio/simpleos/releases/download/v0.6.1/simpleos-0.6.1-x86_64.AppImage
https://github.com/eosrio/simpleos/releases/download/v0.6.1/simpleos_0.6.1_amd64.deb
