### ISSUE TITLE
Wallet Error

### ISSUE THREAD

**Issue by nicktography** [eosrio/simpleos#18]
![2018-06-27 10 42 39 am](https://user-images.githubusercontent.com/33800433/41966511-39518972-79f7-11e8-9fef-413870b974ab.jpg)

Anyone else getting this?

**Comment by eosrio** [comment]
Please test with 0.6.1

**Comment by iainmcgirr1971** [comment]
I am using windows 10 Professional exe wallet. I get this every few days .. and asking to upgrade to a new version. As a result I haven't imported my private keys as I simply don't know where the EOS will be stored.

**Comment by eosrio** [comment]
EOS are never stored on the wallet, only the keys are stored. The tokens are linked to your account name on the blockchain. As for your issue, please install the 0.6.1 directly
