### ISSUE TITLE
This app is useless.

### ISSUE THREAD

**Issue by Bluffet** [eosrio/simpleos#21]
It worked OK at ver 0.4. But now it just crashes:

Process:         simpleos [14602]
Path:            /Applications/simpleos.app/Contents/MacOS/simpleos
Identifier:      simpleos
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [281]
Responsible:     simpleos [14602]
User ID:         501

Date/Time:       2018-06-27 15:24:53.744 +0200
OS Version:      Mac OS X 10.9.5 (13F1911)
Report Version:  11
Anonymous UUID: 

Sleep/Wake UUID:

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
  Referenced from: /Applications/simpleos.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: image not found

Binary Images:
    0x7fff644e4000 -     0x7fff64517887  dyld (239.5) <1D3130FE-FE7E-3C4C-8E74-EB51895B6BA5> /usr/lib/dyld
    0x7fff84266000 -     0x7fff842b7ff7  com.apple.audio.CoreAudio (4.2.1 - 4.2.1) <07F2B103-AE29-3118-BBC4-9A72E13B013B> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff84645000 -     0x7fff84656ff7  libz.1.dylib (53) <42E0C8C6-CA38-3CA4-8619-D24ED5DD492E> /usr/lib/libz.1.dylib
    0x7fff84864000 -     0x7fff8488eff7  libsandbox.1.dylib (278.11.2) <5C750008-A22B-35E8-8B11-D84F82E08680> /usr/lib/libsandbox.1.dylib
    0x7fff84898000 -     0x7fff84898ffd  com.apple.audio.units.AudioUnit (1.10 - 1.10) <68B21135-55A6-3563-A3D6-3E692A7DEB7F> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff85a43000 -     0x7fff85a46ffc  com.apple.IOSurface (91.3 - 91.3) <E93485CC-12B1-318E-BAE3-AB532B264935> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff85d12000 -     0x7fff85d13ff7  libSystem.B.dylib (1197.1.1) <72A98ACC-7606-3AD5-82AF-02D4EBBD4F02> /usr/lib/libSystem.B.dylib
    0x7fff85e3a000 -     0x7fff85e99fff  com.apple.framework.CoreWLAN (4.3.3 - 433.48) <1F17FA12-6E84-309D-9808-C536D445FA6E> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff85ecf000 -     0x7fff85f3bfff  com.apple.framework.IOKit (2.0.1 - 907.100.14) <10932113-9F7E-38A0-A158-A019A555CAC3> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff86435000 -     0x7fff86589ff3  com.apple.audio.toolbox.AudioToolbox (1.10 - 1.10) <69B273E8-5A8E-3FC7-B807-C16B657662FE> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff86825000 -     0x7fff8682fff7  com.apple.bsd.ServiceManagement (2.0 - 2.0) <2D27B498-BB9C-3D88-B05A-76908A8A26F3> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff86a56000 -     0x7fff86c3bfff  com.apple.CoreFoundation (6.9 - 855.17) <729BD6DA-1F63-3E72-A148-26F21EBF52BB> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff86c8f000 -     0x7fff86effffd  com.apple.security (7.0 - 55471.14.40) <58F50B4A-FC1E-3AE0-A5DB-DD737E50AC17> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff86f00000 -     0x7fff86f00fff  com.apple.ApplicationServices (48 - 48) <3E3F01A8-314D-378F-835E-9CC4F8820031> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff871e4000 -     0x7fff87209ff7  com.apple.CoreVideo (1.8 - 117.2) <4674339E-26D0-35FA-9958-422832B39B12> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff8814d000 -     0x7fff8814dfff  com.apple.quartzframework (1.5 - 1.5) <3B2A72DB-39FC-3C5B-98BE-605F37777F37> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff88505000 -     0x7fff8854efff  com.apple.CoreMedia (1.0 - 1273.57) <74FA3D80-A6DB-331A-B32A-683C8E0CC0A6> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff885e4000 -     0x7fff885f4fff  libbsm.0.dylib (33) <2CAC00A2-1352-302A-88FA-C567D4D69179> /usr/lib/libbsm.0.dylib
    0x7fff88ba5000 -     0x7fff88bd3ff7  com.apple.securityinterface (9.0 - 55047) <0346D8A9-2CAA-38F3-A741-5FBA5E9F1E7C> /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
    0x7fff88d0b000 -     0x7fff88d0bfff  com.apple.Accelerate (1.9 - Accelerate 1.9) <509BB27A-AE62-366D-86D8-0B06D217CF56> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff8a249000 -     0x7fff8a257fff  com.apple.opengl (9.6.5 - 9.6.5) <4FAEADD8-EEB3-3FD9-ADC6-BA65806228CC> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff8a5a3000 -     0x7fff8a73fff3  com.apple.QuartzCore (1.8 - 332.4) <CFB972D1-FA37-380C-9A47-2A67A84B7442> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff8bb4f000 -     0x7fff8c6c5ff7  com.apple.AppKit (6.9 - 1265.21) <9DC13B27-841D-3839-93B2-3EDE66157BDE> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff8c6c6000 -     0x7fff8c9c6ff7  com.apple.Foundation (6.9 - 1056.17) <E0B0FAF6-5CA8-3EEB-8BF2-104C0AEEF925> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff8e519000 -     0x7fff8e560ff7  libcups.2.dylib (372.6) <CBD2F0CF-FA10-36E1-A1D5-1B946B45B3B3> /usr/lib/libcups.2.dylib
    0x7fff8e561000 -     0x7fff8e5f5ff7  com.apple.Bluetooth (4.2.7 - 4.2.7f5) <A7F0360A-DBDA-32EA-AA37-6937B94E6A72> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fff8e81f000 -     0x7fff8e81ffff  com.apple.Carbon (154 - 157) <EFC1A1C0-CB07-395A-B038-CFA2E71D3E69> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff8e85f000 -     0x7fff8ecadfef  com.apple.VideoToolbox (1.0 - 1273.57) <AA4D613A-1066-3E85-8BE0-7806566652B4> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff8f766000 -     0x7fff8f888fff  com.apple.avfoundation (2.0 - 651.12.1) <FDCF1F41-E0BD-3F8C-974A-3F48A0A85B00> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff8f889000 -     0x7fff8f8dbfff  libc++.1.dylib (120) <4F68DFC5-2077-39A8-A449-CAC5FDEE7BDE> /usr/lib/libc++.1.dylib
    0x7fff8fba4000 -     0x7fff8fbc0fff  libresolv.9.dylib (54) <11C2C826-F1C6-39C6-B4E8-6E0C41D4FA95> /usr/lib/libresolv.9.dylib
    0x7fff904d6000 -     0x7fff90617fff  com.apple.QTKit (7.7.3 - 2826.34) <3BB88D64-71FA-3824-A52A-D51C761E6EE0> /System/Library/Frameworks/QTKit.framework/Versions/A/QTKit
    0x7fff90685000 -     0x7fff90820ff8  com.apple.CFNetwork (673.6 - 673.6) <CAA196FE-BF5A-384F-975E-E0F81359805B> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff908e0000 -     0x7fff90943ffb  com.apple.SystemConfiguration (1.13.1 - 1.13.1) <339A2A90-DA25-33AF-88E5-2FB38A758FEE> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration

Model: MacPro4,1, BootROM MP41.0081.B07, 8 processors, Quad-Core Intel Xeon, 2.26 GHz, 24 GB, SMC 1.39f5
Graphics: ATI Radeon HD 4870, ATI Radeon HD 4870, PCIe, 512 MB
Memory Module: DIMM 1, 4 GB, DDR3 ECC, 1066 MHz, 0x859B, 0x435435313237324241313036372E4D313846
Memory Module: DIMM 2, 4 GB, DDR3 ECC, 1066 MHz, 0x859B, 0x435435313237324241313036372E4D313846
Memory Module: DIMM 3, 4 GB, DDR3 ECC, 1066 MHz, 0x859B, 0x435435313237324241313036372E4D313846
Memory Module: DIMM 5, 4 GB, DDR3 ECC, 1066 MHz, 0x859B, 0x435435313237324241313036372E4D313846
Memory Module: DIMM 6, 4 GB, DDR3 ECC, 1066 MHz, 0x859B, 0x435435313237324241313036372E4D313846
Memory Module: DIMM 7, 4 GB, DDR3 ECC, 1066 MHz, 0x859B, 0x435435313237324241313036372E4D313846
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8E), Broadcom BCM43xx 1.0 (5.106.98.100.22)
Bluetooth: Version 5.2.7f4 15858, 3 services, 23 devices, 1 incoming serial ports
Network Service: Ethernet 2, Ethernet, en1
Network Service: AirPort, AirPort, en2
PCI Card: ATI Radeon HD 4870, Display Controller, Slot-1
Serial ATA Device: HL-DT-ST DVD-RW GH41N
Serial ATA Device: Hitachi HDE721064SLA360, 640,14 GB
Serial ATA Device: OCZ-VERTEX4, 512,11 GB
USB Device: Hub
USB Device: Hub
USB Device: Bose USB Audio
USB Device: Apple Cinema HD Display
USB Device: Hub
USB Device: Keyboard Hub
USB Device: Microsoft ® Laser Mouse 6000
USB Device: Apple Keyboard
USB Device: Apple Cinema HD Display
USB Device: USB Receiver
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
FireWire Device: built-in_hub, Up to 800 Mb/sec
FireWire Device: My Book, WD, Up to 800 Mb/sec
FireWire Device: My Book, WD, Up to 800 Mb/sec
Thunderbolt Bus:

**Comment by rreeve** [comment]
Yours has crashed on Apple. So has mine on Windows. There is definitly an issue with SimplEOS at the moment. 
![simpleeos error](https://user-images.githubusercontent.com/8009013/41979501-23e17780-7a1c-11e8-84fa-8a4ab9d6de65.JPG)

**Comment by eosrio** [comment]
Please uninstall any version prior to 0.6 and install 0.6.1
