### ISSUE TITLE
Mac os Yosemite not compatible?

### ISSUE THREAD

**Issue by realcryptoZ** [eosrio/simpleos#22]
When I try to open version 0.6.1 on my mac (version Yosemite) I keep getting the error message below. What should I do to get the wallet to open?

[Screen Shot 2018-06-27 at 11.43.17 PM.pdf](https://github.com/eosrio/simpleos/files/2143659/Screen.Shot.2018-06-27.at.11.43.17.PM.pdf)

**Comment by eosrio** [comment]
Can you try with version 0.6.2 ? We don't have a older mac at hand to test :(
