### ISSUE TITLE
404 Error popup in v0.6.1 when update to v0.6.2 became available

### ISSUE THREAD

**Issue by stevang** [eosrio/simpleos#25]
i am on windows and on v0.6.1
as v0.6.2 became available, i got this 404 error popup about ../v0.6.2/latest.yml

![image](https://user-images.githubusercontent.com/5052540/42083297-c40525a8-7b8a-11e8-94ec-515189818fee.png)

Regards,
Stephan

**Comment by eosrio** [comment]
That's completely fine Stephan, we removed the updater. So just download the new version it will update locally.
