### ISSUE TITLE
Getting error dialog when clicking on Send in SimplEOS

### ISSUE THREAD

**Issue by opadilla** [eosrio/simpleos#27]
Unfortunately, it doesn't allow me to copy and paste the message...   Here's the beginning of the error:

Cannot find latest.yml in the latest release artifacts.

It appears to work OK after I close the error dialog but you can imagine how concerning this will be to people.  I've been telling people in youtube and twitter to use your wallet by the way.  Keep up the good work.

**Comment by eosrio** [comment]
Please update manually to 0.6.2, this is fixed. Thanks
