### ISSUE TITLE
"Next" button greyed out in Create New Account step 3

### ISSUE THREAD

**Issue by nagumii** [eosrio/simpleos#34]
When creating a new account (after already associating an old private key), then selecting "associated with a new private key" you can't click "next" in step 3 ("define keys") after generating new keys.

**Comment by eosrio** [comment]
Thanks for the report, we need to investigate this further

**Comment by dscotese** [comment]
This is still happening in the 0.6.2-4: I just downloaded and ran 0.6.2-4 because I entered my "desired public keys" as instructed under "New Account" but the "Next" button remains disabled.  My goal is to add a new address to SimplEOS under the existing owner public key.

**Comment by justinjmoses** [comment]
This happens for me even just trying to Request a New Account. The "next" button won't re-enable even after generating keys (regardless of whether or not I'm connected to the internet). 

This makes the software unusable for a new user 😞

**Comment by justinjmoses** [comment]
cc @igorls

**Comment by dscotese** [comment]
Github says I commented on this issue, but I don't see any comment from me on this issue.  Any ideas?
