### ISSUE TITLE
Airdrops not showing in v0.6.2-1 on Mac OS X

### ISSUE THREAD

**Issue by nicktography** [eosrio/simpleos#37]
Airdrops no longer show in the sidebar...
![ssp_temp_capture copy](https://user-images.githubusercontent.com/33800433/42286900-3b69bd50-7fac-11e8-977b-e17588741324.jpg)

**Comment by eosrio** [comment]
This bug was already detected, it happens when you got a lot of transactions. Will be fixed on the next release.

**Comment by opadilla** [comment]
I'm not seeing all of my airdrops in the Windows version either.

**Comment by iainmcgirr1971** [comment]
Not seeing on latest windows either is there a fix for this 
currently at 6.2-1 as per site

**Comment by rgingery23** [comment]
Was seeing airdrops fine until yesterday.  Now only 3 show up.

**Comment by igorls** [comment]
Thanks for the report. Was fixed on https://github.com/eosrio/simpleos/releases/tag/v0.6.3-2

**Comment by SingularityMatrix** [comment]
FYI - after updating to v0.6.3-2, still the airdrops are not showing up. For me, only the EOS balance is shown.
