### ISSUE TITLE
showing errors but still seams to work.

### ISSUE THREAD

**Issue by honestdude** [eosrio/simpleos#38]
when opening wallet after the update I am showing three error reports in a row. this is the message
[first Error.docx](https://github.com/eosrio/simpleos/files/2164537/first.Error.docx)

After clicking OK, twice, "it shows the same message twice" I get a third new error message:

[Error2.docx](https://github.com/eosrio/simpleos/files/2164540/Error2.docx)

after clicking OK, it brings up my "small" balance and appears to work as intended but I have not attempted any transaction as of yet.

This happened some days ago and I neglected to report it until now. sorry. But noteworthy is that now the first two error messages to not show anymore but the third longer message still shows whenever I open the wallet. 

I am using version 0.5.5 on a MacBook running 10.13.1

**Comment by honestdude** [comment]
After updating to 0.6.2-1 The error messages are no longer showing. I am still getting used to this github process. should I close this issue?

**Comment by eosrio** [comment]
Yes, Thanks. We can close this now
