### ISSUE TITLE
Pagination is not showing more than one page on initial load

### ISSUE THREAD

**Issue by QuentinDejean** [eosrio/simpleos#4]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
On initial load of the wallet, the pagination shows that only one page is available. See image below:
<img width="925" alt="simpleos_wallet" src="https://user-images.githubusercontent.com/1570025/41450266-e071dce0-70a9-11e8-8c18-d8a73faea4cc.png">

**What is the expected behavior?**
I should see more than one page available. See image below:
<img width="913" alt="simpleos_wallet" src="https://user-images.githubusercontent.com/1570025/41450334-4158eba2-70aa-11e8-913d-a95a9ddd76a6.png">

**Comments**
This _only_ happens on very first load of the wallet. Switching back and forth between "History" and "Vote" tabs fix the issue.

I suspect there is either a racing condition on first load, or simply that the component is not listening correctly for data to be loaded

**Comment by eosrio** [comment]
Fixed on 0.5.5+
