### ISSUE TITLE
Wrong Password error

### ISSUE THREAD

**Issue by luismsmendonca** [eosrio/simpleos#40]
simpleos always gives "wrong password!" error. whenever trying to vote or send eos.  Tried multiple times to clear local data and add again. The version I tried was version 0.6.2-1, macosx and windows versions yield same error.

**Comment by IamCryptoRush** [comment]
Trying to send EOS but receiving wrong password message. I'm definitely using the right password. I am using the 0.6.2-1exe version for windows

**Comment by dscotese** [comment]
You may have imported a key for your account that doesn't have the permissions required for sending or voting.  I came here to github because I wanted to recommend that if the key to import ought to be the Active key, then the wallet should ask for that one, and if what you can do with your wallet depends on which key you import, it should explain that. And when you try to change your password and it fails because you didn't import your Active key, it should say so.

Really, for the two of you, consider joining the [eosrio telegram group](https://t.me/eosrio).

**Comment by IamCryptoRush** [comment]
I actually got it to work by sending a small amount for a test. But when I
tried to send the full account I got the wrong password error again. I had
to log in and out a few times then suddenly it worked.

**Comment by andrejcibik** [comment]
I tried to import both owner or active private keys multiple times, resting, cleaning the AppData folder, downloading new version - no luck. Wrong password error still remains.

**Comment by joezys** [comment]
I wanted to stake more EOS tokens purchased from an exchange and moved to my SimpleEOS wallet but I get the "wrong password" error and am unable stake my purchased tokens.  Other problems I'm experiencing include no history or any sort, and no airdrop tokens appearing in this wallet.  Why isn't EosRIO doing more to resolve these issues that have been going on for over 2 weeks.  I' liked this wallet when it worked, but I'm getting ready to switch to another wallet.

**Comment by mikeborghi1** [comment]
POTENTIAL SOLUTION:

Conditions: 
OSX 0.6.2-4 
Transferred over from the erc token using exodus' built in tool
Successfully unstaked and sent a majority of those tokens and decided to leave a minute amount staked for the hell of it.  
Point being, i had successfully used this wallet multiple times and the password i wrote down that i have no recollection of changing is no longer working.

Symptoms:
Today comes and i decide i want to invest some more money into EOS and i withdraw it to my wallet.  Upon moving the slider i was asked to enter a password and when i typed/copied and pasted, etc over and over again, i kept getting the same error. Even with sending i would get an error.

I updated to the most recent version 0.6.3-2 and got a weird new scenario.`

Upon triggering the enter password modal for sending, it would give the following error only a single time before going back to the regular wrong password one, and closing and resending the transaction to trigger the modal made it appear again and it would only trigger this warning  with the correct password:
(apologies, had to go off of what i googled, but this contains every word in the error message minus a couple)
`EOSIO assert message assertion failure
`
Again, only the first click would generate this.

**HOWEVER**

Upon going to the change password screen and restarting (which it forces you to do upon password changing), i was able to send with my new password with no problem.

I hope someone else is helped by this and i provided as much as i could to the developer.  I can't find any logs, only and empty ~/Library/logs/simpleos folder.  

All the best,

MB

P.S. I'm not at all familiar with eos other than what the average trader is.

**Comment by igorls** [comment]
Please check again on the new release, https://github.com/eosrio/simpleos/releases/tag/v0.6.4
