### ISSUE TITLE
simplEOSupdate 

### ISSUE THREAD

**Issue by John-29** [eosrio/simpleos#41]
update 0.6.2-1 overrides previous installation and asks for pin. No pin was previously used,
"Forgot pin?" tab is grayed out. Can not access acount.

**Comment by CryptoHusker2017** [comment]
It's been a while since that happened to me; but I think there's a setup as new option. I believe you'll need your private key again.

**Comment by John-29** [comment]
Thanks for your answer, but there seems to be no way to do that. The program asks for the pin at startup, and no other options are available.

**Comment by igorls** [comment]
Please update to latest version and clear your local data if you come from a version which didn't had the pin.
https://github.com/eosrio/simpleos/releases/tag/v0.6.4
