### ISSUE TITLE
can't connect to the blockchain

### ISSUE THREAD

**Issue by juergenbraatz** [eosrio/simpleos#44]
Although i'm online i can't connect to the blockchain for hours now :(

**Comment by ZAREOS** [comment]
same issue as juergenbraatz

**Comment by francisdv** [comment]
same issue for me

**Comment by jeremydrahos** [comment]
In the endpoint part, put https://eos.greymass.com and try again

**Comment by igorls** [comment]
Please check again on the new release, https://github.com/eosrio/simpleos/releases/tag/v0.6.4
we included a feature to connect on custom endpoints
