### ISSUE TITLE
Airdops not showing Windows 10

### ISSUE THREAD

**Issue by TPodgis** [eosrio/simpleos#46]
Airdrops do not show on the right side of screen. Under the send tab, can not access airdrops.
Version 06.2-4

**Comment by iainmcgirr1971** [comment]
Same here ..version 6.2-1 downloaded .. now not showing at all only the eos ..nothing no eos dac etc. etc.

**Comment by joezys** [comment]
I'm having the same issue with Windows 7.  Also, history doesn't show transfers of EOS tokens from an exchange, however, the total amount of EOS is correct, including staked and unstaked amounts. History does not show any airdropped tokens, nor does the column to the right.  Just checked my balance on eosflare.io and my airdrop tokens still appear there, they just no longer appear in my simpleos wallet.

**Comment by jvaught74** [comment]
Having a similar issue.  I can see my eosdac and ADD, but on eosflare I have several other airdrops that aren't showing in my account.

**Comment by Joohansson** [comment]
Same here with 6.2-1. They were all there some week or two ago, but now only show eosDac. I tried clean all data but didn't help. eosflare.io show correct tokens.

**Comment by cryptomartin** [comment]
Same here (Windows 10)

**Comment by igorls** [comment]
Thanks for the report. Was fixed on https://github.com/eosrio/simpleos/releases/tag/v0.6.3-2
