### ISSUE TITLE
Voting history not updating.

### ISSUE THREAD

**Issue by curiousbanana** [eosrio/simpleos#47]
I have tried voting a number of times and a green pop up box appears saying to check my history to see votes. However, my history doesn't update and the most recent transactions shown are 22 days old. This is with versions 0.6.2-1 and the latest 0.6.2-4.

**Comment by Joohansson** [comment]
Same here, win10 and 0.6.2-4. My latest history is 1 month old. The tokens are now back at least but no price info as it was from the beginning.

**Comment by igorls** [comment]
Please check again on the new release, https://github.com/eosrio/simpleos/releases/tag/v0.6.4
