### ISSUE TITLE
"Generate Key Pairs" button should not need to be clicked to see entry fields for private keys.

### ISSUE THREAD

**Issue by dscotese** [eosrio/simpleos#48]
If I knew Angular better, I'd alter the existing code so that before displaying the wizard page at line 145 of /src/app/dashboard/dashboard.component.html the generate() function would be called so that `generated` would be true and the fields for the private keys would be visible.  Then we could update the instructions (lines 149-151) to say "If you'd like to use your own keys, please paste them into the fields below.  You may also press the 'Generate Key Pairs' button for new keys, or continue with those displayed below."

**Comment by igorls** [comment]
We believe and encourage the user to generate his keys with the method he deem secure enough.

**Comment by dscotese** [comment]
Me too!  That's why I think the fields into which you can paste your private keys should show up when you start the wizard.  I've implemented this in pull request #49.  Have you checked it out?
