### ISSUE TITLE
Add BP ranking to Voting page

### ISSUE THREAD

**Issue by QuentinDejean** [eosrio/simpleos#5]
**Do you want to request a feature or report a bug?**
Feature

**What is the current behavior?**
The Voting page does not display the ranking of the BPs on the table. It is unclear which ones are the top 21 BPs, and which ones are in the "queue"

**What is the expected behavior?**
Have a way to reference the top 21 BPs in the table. It could be:
- a simple number as the first column of each row
- a different background colour for the first 21 rows

**Comments**
If validated as a useful enhancement, I'm happy to raise a PR for that

**Comment by eosrio** [comment]
Maybe using an icon to indicate active/stand-by, do you have any suggestion?

**Comment by QuentinDejean** [comment]
Quickly mocked this up on my machine:
<img width="437" alt="screen shot 2018-06-15 at 4 09 31 pm" src="https://user-images.githubusercontent.com/1570025/41452741-8e1378d4-70b6-11e8-9f40-7f0e10f143a6.png">

Could be great to also have some different background colours for the top 21, to make it clear which ones are on standby and which ones are not. I can't really find your colour palette in the app (primary tones of colours), any input on that?

**Comment by pegaltier** [comment]
Hello, nice app, just installed on my machine and it work good, i love angular so i will pull regularly the codebase and i will try to help you !
@QuentinDejean I'm french from south o France and you?

**Comment by eosrio** [comment]
@pegaltier We will enable something that might help you on the next release ;) Wait a little bit. Sorry for the late reply
