### ISSUE TITLE
Airdrop tokens not showing correct balances. (Linux 0.6.2-4) 

### ISSUE THREAD

**Issue by DanDroidOS** [eosrio/simpleos#50]
The airdrop tokens are showing incorrect balances.

**Comment by joezys** [comment]
I still have no airdrop token balances showing in my SimpleEOS wallet, and now no history.

**Comment by igorls** [comment]
Thanks for the report. Was fixed on https://github.com/eosrio/simpleos/releases/tag/v0.6.3-2
