### ISSUE TITLE
Config not working (Windows 0.6.2-4)

### ISSUE THREAD

**Issue by pegaltier** [eosrio/simpleos#51]
When i click config (up right button) the current screen (history or send or vote) close but nothing else open and i get nothing.

I installed project locally to debug and it work using chrome browser so maybe it's due to electron.

No matter, thanks for your work, I voted for you!

**Comment by igorls** [comment]
Thanks for the report. Was fixed on https://github.com/eosrio/simpleos/releases/tag/v0.6.3-2
