### ISSUE TITLE
Can't connect to the Endpoint

### ISSUE THREAD

**Issue by kenneth** [eosrio/simpleos#53]
Couldn't connect to the blockchain, check your internet connection and try again

**Comment by kenneth** [comment]
solved,change a endpoint

**Comment by TheDoktar** [comment]
Using simpleos_0.6.2_amd64.deb I get the same issue. 
There is an  invitation to connect to http://br.eosrio.io:8080 but this also fails.

**Comment by kenneth** [comment]
http://br.eosrio.io:8080 can't connect but you can use http://api.eosrio.io

**Comment by TheDoktar** [comment]
Thanks, 0.6.2.4 seems to fix the
      problem out of the box. 
      
      regards, 
      
          Mark 
      
      
      On 25/07/18 08:56, Kenneth wrote:
    
    
      
      http://br.eosrio.io:8080 can't
        connect but you can use http://api.eosrio.io
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/eosrio/simpleos","title":"eosrio/simpleos","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/eosrio/simpleos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kenneth in #53: http://br.eosrio.io:8080 can't connect but you can use http://api.eosrio.io"}],"action":{"name":"View Issue","url":"https://github.com/eosrio/simpleos/issues/53#issuecomment-407667813"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/eosrio/simpleos/issues/53#issuecomment-407667813",
"url": "https://github.com/eosrio/simpleos/issues/53#issuecomment-407667813",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [eosrio/simpleos] Can't connect to the Endpoint (#53)",
"sections": [
{
"text": "",
"activityTitle": "**Kenneth**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@kenneth",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"eosrio/simpleos\",\n\"issueId\": 53,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"eosrio/simpleos\",\n\"issueId\": 53\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/eosrio/simpleos/issues/53#issuecomment-407667813"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 359190721\n}"
}
],
"themeColor": "26292E"
}
]
