### ISSUE TITLE
Assertion Failure

### ISSUE THREAD

**Issue by llmystice** [eosrio/simpleos#56]
I am not able to stake my tokens and the message im getting reads, Eosio_assert_message
                                                                                                                   Assertion Failure
I should say Icannot stake the remaining of my EOS. Also , my voting history is showing up, but not the airdrop history or the airdrops.

**Comment by igorls** [comment]
Please test with the latest release. It should be fixed ;)

**Comment by ifavo** [comment]
Me too, but it happens only when trying to send IQ tokens.
