### ISSUE TITLE
6.3.2 not showing tokens again

### ISSUE THREAD

**Issue by iainmcgirr1971** [eosrio/simpleos#59]
Seemed to be fixed for 6.2.4 ..using windows 10 Professional wallet .. now again its gone my tokens are not showing.. why ..why ..why this constant working non working... etc..

**Comment by ebout** [comment]
airdrop tokens not displaying on 6.2 currently (although they did
before).. I AM HESITANT TO ACTIVATe THE 6.3.2 IF IT IS STILL HAVING
PROBLEMS WITH DISPLAYING TOKENS.

**Comment by ebout** [comment]
When is 6.3.3 coming out?

**Comment by igorls** [comment]
Issue should be fixed now - https://github.com/eosrio/simpleos/releases/tag/v0.6.4
