### ISSUE TITLE
Error 0.5.0

### ISSUE THREAD

**Issue by Rolthar** [eosrio/simpleos#6]
Hey guys, just installed the newest version 0.5.0, when I open up SimplEOS, i get the error 
"TypeError: Cannot read property 'send' of undefined as NsisUpdater.autoUpdater.on"

Voting still works, however adjusting your stake does not.. after i enter my password to change my stake, it says 'something went wrong'.

Hope this helps iron out any more bugs :) 
Cheers!

**Comment by eosrio** [comment]
@Rolthar 1 EOS (0.5 for CPU and 0.5 for bandwidth) is the safe minimum to guarantee action execution on the chain, so we limited the full unstaking to avoid users losing functionality of their accounts. If you really know what you are doing and want to perform a full unstake you must use cleos (command line tool) to push the action

**Comment by eosrio** [comment]
`Cannot read property 'send' of undefined as NsisUpdater.autoUpdater.on` is fixed on 0.5.1 patch

**Comment by Rolthar** [comment]
Awesome, thanks for the info and great work on the quick patch fix :)
