### ISSUE TITLE
Unable to unstake my tokens

### ISSUE THREAD

**Issue by Ray3212** [eosrio/simpleos#60]
I am just Unable to unstake my tokens, after setting the amount and entering password press confirm and nothing happens... I have tried multiple times.

**Comment by santangeli** [comment]
Same problem, cant unstake. To me always appear a message "Account using more than allotted RAM usage", even with only simpleos running and ata machine with 16 giga ram ;)

**Comment by aexmachina** [comment]
Same problem, but no message appears.

**Comment by santangeli** [comment]
Well, i resolved using another wallet (had to spend a few eos to increase my memory, this is in blockchain, not on our physical machine), after that i could unstake.

**Comment by aexmachina** [comment]
What wallet did you use @santangeli?

**Comment by santangeli** [comment]
eos-voter. I could buy RAM with it and after that, it's possible to unstake the token (you can sell the RAM after the unstake also)

**Comment by sensay-nelson** [comment]
same problem, can not unstake.  can ram be purchased through simpleos?

**Comment by santangeli** [comment]
I did not find a way to do that using simpleos :(

**Comment by yellowfin22** [comment]
I had the same problem with simpleos. Got this email from their support and then it worked fine...

First thing is to check wether you're on simplEOS latest version (0.6.4). If you're not on it, please update on https://eosrio.io/simpleos/

If you're on v 0.6.4 that's usually an endpoint problem. It means the endpoint you are using has a high latency or that the network is congested. When you enter SimplEOS, the wallet automatically chooses the fastest endpoint to you, but sometimes this changes in the middle of the session. 

When this happens, close and reopen the wallet. Than go to the configurations panel (cog symbol on the upper right corner). There, you will see endpoint options. Just click on one that you think is better or click ‘AUTO’ (this recalculates the latencies and chooses the best endpoint for them).

**Comment by igorls** [comment]
closing this issue since its not happening on the current version (0.7.1)
