### ISSUE TITLE
not connecting to blockchain

### ISSUE THREAD

**Issue by StevenAbaby** [eosrio/simpleos#66]
This is my first use after installation and putting in my EOS.  When I open SimplEOS I get a message "Couldn't connect to the blockchain".  See attached.  I tried clicking on the "Help" icon, but THERE IS NO HELP ICON!  Another message says I can try to connect to another endpoint but when I click "connect" I again get the "Couldn't connect to the blockchain message.  My internet connection seems to be working because I am able to bring up github.  When I try to go to http://br.eosrio.io:8080 in my Chrome browser it fails.  When I try http://br.eosrio.io I get a generic nginx message that say the web server is installed but needs additional configuration.  When I left a message on https://eosrio.io/faq/ I got no response.
![simpleos](https://user-images.githubusercontent.com/30455141/46318105-3a5afb80-c58a-11e8-9329-d191f282b1d8.png)

**Comment by durbanboy** [comment]
Same here
