### ISSUE TITLE
Pin function not working

### ISSUE THREAD

**Issue by Mrlodak** [eosrio/simpleos#75]
I enter my pin and click unlock and nothing happens in the latest version. Yes I'm sure I'm using the right pin it simply just doesn't do anything.

**Comment by iht76** [comment]
same here

**Comment by captaincrypton** [comment]
downloaded and installed updated wallet pin function will not work.

**Comment by igorls** [comment]
the pin compatibility with the old version was broken, we removed the release now and will patch it up

**Comment by igorls** [comment]
this issue is fixed now on v0.7.1

**Comment by ron931** [comment]
Hi, I downloaded V0.7.2 back in February. Everything worked fine. I backed up my public and private files. It now says that my private file is invalid when I try to access my wallet. I can verify my wallet with my public key. Can anyone provide help with this issue?
