### ISSUE TITLE
New Update 0.6.9 not showing any transactions 

### ISSUE THREAD

**Issue by workin2005** [eosrio/simpleos#76]
Since downloading 0.6.9, none of my transactions are showing. Also, when trying to vote, after entering my password, it just sits there and does nothing. It doesn’t say “wrong password” or anything...it just sits there.

**Comment by workin2005** [comment]
<img width="958" alt="screen shot 2019-01-11 at 7 05 45 pm" src="https://user-images.githubusercontent.com/34941505/51065680-25075b80-15d4-11e9-9569-95b7ac077b7f.png">

**Comment by igorls** [comment]
we just released 0.7.1 today, please test on it

as for the history, we recommend that you double-check everything on a block explorer
