### ISSUE TITLE
Add switch dev/main net

### ISSUE THREAD

**Issue by pegaltier** [eosrio/simpleos#8]
It can be a good idea to add switch devnet/mainnet, for example we can use this following server:
http://vote.eosio.sg/

For example inside the constructor
  testEndpoints: Endpoint[];

    this.testEndpoints = [
       {url: 'http://13.251.3.82:8888', owner: 'EOS vote.eosio.sg', latency: 0, filters: []}, // TEST 
    ];

But we need also to change the variables for : mainnetId, genesistx and voteref

Can someone know this last variables for this devnet server http://vote.eosio.sg ?

Thanks

**Comment by igorls** [comment]
We just need the chainID, the other 2 are used for api validation, in the case of a testnet they can be ignored

**Comment by ebout** [comment]
Got non-programmer questions.  
1. Why aren't all of my tokens staked? (10 are unstaked). 
 and 
2. Instead of showing a send/receive option page for 
sending to wallets and exchanges.  Only a send tab is shown and it is preset to send the 10 unstaked tokens.

**Comment by eosrio** [comment]
Hi @ebout , what you experienced is normal, all eos accounts started with almost everything staked and only max 10 eos free (unstaked). After mainnent was activated users could unstake and free their eos. But keep in mind the unstaking process takes 3 days to be completed, your tokens will only be free for transfers after 3 days (this is the way eos code was written, this has nothing to do with the wallet). 

We released version 0.3.5 with the stake / unstaking feature. The feature can be found on the VOTE page.

**Comment by pegaltier** [comment]
@igorls i think the chainId for testnet vote.eosio is : 0000000000000000000000000000000000000000000000000000000000000003
Source: https://github.com/eosiosg/Vote-testnet/blob/master/genesis.json

But it doesn't work

**Comment by eosrio** [comment]
@pegaltier We will implement support for custom chains soon
