### ISSUE TITLE
Cannot connect to Blockchain issue

### ISSUE THREAD

**Issue by emperorjm** [eosrio/simpleos#9]
Running locally using "**yarn run start**" for development purposes I'm getting a "**Couldn't connect to the blockchain, check your internet connection and try again**" error even though all the latency and filter checks for each BP are successful and the best server is selected.

"**src/app/network.service.ts**" line 62 has "**this.networkingReady.next(false);**" which is causing the error. When set to "true" the app loads with no issues.

I have not executed the app using the production settings but I believe it would be the same issue. Could there be some other issue why this is happening?

**Comment by eosrio** [comment]
Thanks! We will look into that

**Comment by eosrio** [comment]
Probably fixed on 0.5.6, please test it out!
